### ISSUE TITLE
Stub out dashboard page 

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/slarx-deposit-ui#4]
See description of dashboard page in this working doc https://docs.google.com/document/d/1BH3L25QYoo-WM7NxitTapsaQtjonvEZx-t4aO3I36mE/edit

This ticket is dependent on the out come of the [Deposit UI data model ticket](https://github.com/jhu-sheridan-libraries/slarx-general-issues/issues/3). 

please expect changes in the future, but it'd be good to put something down for now.

**Comment by jabrah** [comment]
https://github.com/jhu-sheridan-libraries/slarx-deposit-ui/pull/7 has a super simple stub, without much layout, but includes some important Submissions info. There is still more that should be displayed to the user, like notifications about scan results

**Comment by jabrah** [comment]
I think this is safe to close. Stub is in place, so further implementation can be tracked with separate ticket(s)
